import ThemeRegistry from './ThemeRegistry';

import { Montserrat } from 'next/font/google';

import './globals.css';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: 'Tiago Davila',
  description: 'Generated by Tiago Davila',
};

// app/layout.js
export default async function RootLayout(props) {
  const { children } = props;

  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
